# app/config/settings.yml
defaults: &defaults
  system_settings:
    app_name: "移动学习平台"
  pagination:
    per_page: 20
  cool:
    saweet: nested settings
  neat_setting: 24
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults